databases:
  - name: fakebnb
    databaseName: fakebnb
    user: fakebnb
    region: singapore

services:
  - type: web
    name: mysfakebnbite
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fakebnb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4